{{ if .Values.blue.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  {{ .Release.Name }}-blue
  name:  {{ .Release.Name }}-blue
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-blue
    type: {{ .Values.blue.Type }} 
  type: ClusterIP
{{ end }}
